name: Build Godot Android Game

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Godot Android
        uses: abarrak/godot-ci@main
        with:
          name: my_game
          # هنا نقول للسيرفر أن يبحث عن الملفات في المجلد الرئيسي
          android: true
